# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-07 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='comentario',
        ),
        migrations.AddField(
            model_name='comentario',
            name='tarea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.Tarea'),
        ),
    ]
