# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-13 22:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tareas', '0003_auto_20170916_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='asignado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas_asignada', to=settings.AUTH_USER_MODEL),
        ),
    ]
