# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-06 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_auto_20170916_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='asignado',
            field=models.TextField(default=' ', max_length=20),
        ),
    ]
